version: "3.9"
services:
  spid:
    image: "italia/spid-saml-check:1.10.4"
    ports:
      - "8443:8443"
  web:
    build:
      context: .
      args:
        - BASE_PATH="v1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 3s
    depends_on:
      spid:
        condition: service_started
    ports:
      - 8000:8000
